---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: currencyservice
  namespace: develop
  annotations:
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: semver:~v0.0
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/charts/currencyservice
      version: 'x.x.x'
      sourceRef:
        kind: GitRepository
        name: deployrepo
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: daniilrostov/currencyservice
      tag: v0.0.1
