---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recommendationservice
  namespace: develop
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/charts/recommendationservice
      version: 'x.x.x'
      sourceRef:
        kind: GitRepository
        name: deployrepo
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: daniilrostov/recommendationservice
      tag: v0.0.1
