apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol:all-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-reader
subjects:
  - kind: Group 
    name: system:serviceaccounts:prometheus 
    namespace: prometheus
