apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
        - name: nginx-service
          image: daniilrostov/nginx_status
          ports: 
            - name: web
              containerPort: 80
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter:0.10.0'
          args:
            - '-nginx.scrape-uri=http://localhost//basic_status'
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - name: exporter
              containerPort: 9113
