apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: exporter
  endpoints:
    - port: exporter
