apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    prometheus: prometheus
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: exporter
  type: NodePort
