apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}