---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: semver:~v0.0
spec:
  interval: 1m
  chart:
    spec:
      chart: istiod
      version: 'x.x.x'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
