---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: semver:~v0.0
spec:
  interval: 1m
  chart:
    spec:
      chart: gateway
      version: 'x.x.x'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
  values:
    service:
      ports:
        - name: kiali
          port: 20001
          protocol: TCP
          targetPort: 20001
        - name: kiali2
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: frontend
          port: 80
          protocol: TCP
          targetPort: 80
        - name: grafana
          port: 3000
          protocol: TCP
          targetPort: 3000
        - name: jaeger
          port: 16686
          protocol: TCP
          targetPort: 16686
