apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
    - name: mypod2
      image: nginx
      volumeMounts:
        - mountPath: "/app/data"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: my-pvc