apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем

metadata:
  name: testkuber # Название Pod
  labels: # Метки в формате key: value
    key: web 
spec: # Описание Pod
  initContainers:
    - name: init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  containers:  # Описание контейнеров внутри Pod
    - name: webdir # Название контейнера
      image: daniilrostov/webdir # Образ из которого создается контейнер
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}